# 默认的profile为dev，其他环境通过指定启动参数使用不同的profile，比如：
#   测试环境：java -jar my-spring-boot.jar --spring.profiles.active=test
#   生产环境：java -jar my-spring-boot.jar --spring.profiles.active=prod
# spring:
#   profiles:
#     active: test
#  cache:
#    type: CAFFEINE #指定cache类型
#    cache-names:
#      - getPersonById
#      - name2
#    caffeine:
#      spec: maximumSize=500,expireAfterWrite=5s
      
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: 123456
#    hikari:
#      maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
#      maximumPoolSize: 15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)

#spring:
#  datasource:
#    druid:
#      url: jdbc:mysql://172.16.13.139:3306/fy?useUnicode=true&characterEncoding=utf8&useSSL=false
#      username: root
#      password: 123456
#
#       #alibaba Druid连接池配置,
#      type:  com.alibaba.druid.pool.DruidDataSource
#      driver-class-name:  com.mysql.jdbc.Driver
#      filters: stat
#      maxActive: 20
#      initialSize: 1
#      maxWait: 60000
#      minIdle: 1
#      timeBetweenEvictionRunsMillis: 60000
#      minEvictableIdleTimeMillis: 300000
#      validationQuery: select 'x'
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      poolPreparedStatements: true
#      maxOpenPreparedStatements: 20

#  mail:
#    host: smtp.exmail.qq.com
#    username: service@mail.cn
#    password: myPassword
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
#    mybatis:
#        mapper-locations: classpath:mapper/*.xml
#        type-aliases-package: com.why.entity
#  server:
#      port: 8082
#  management:
#      server:
#          port: 54001
#  health:
#    mail:
#      enabled: false
#  info:
#   app:
#    name: "@project.name@" #从pom.xml中获取
#    description: "@project.description@"
#    version: "@project.version@"
#    spring-boot-version: "@project.parent.version@"


# 开发环境配置
#spring:
# profiles: dev
#  redis:
#    cluster:
#      nodes:
#        - 192.168.0.11:6390
#        - 192.168.0.11:6391
#        - 192.168.0.11:6392
#        - 192.168.0.9:6390
#        - 192.168.0.9:6391
#        - 192.168.0.9:6392
#  datasource:
#    url: jdbc:mysql://localhost:3306/?serverTimezone=GMT%2B8
#  data:
#    mongodb:
#      uri: mongodb://192.168.0.9,192.168.0.18/test?replicaSet=devRs

#自定义的属性和值
#  my-props:
#   simpleProp: simplePropValue
#   arrayProps: 1,2,3,4,5
#   listProp1:
#    - name: abc
#      value: abcValue
#    - name: efg
#      value: efgValue
#  listProp2:
#    - config2Value1
#    - config2Vavlue2
#  mapProps:
#    key1: value1
#    key2: value2


# 测试环境配置
#  spring:
#     profiles: test
#     datasource:
#       url: jdbc:mysql://172.16.13.139:3306/fy?useUnicode=true&characterEncoding=utf8&useSSL=false


# 生产环境配置
# spring:
#   profiles: prod
#   datasource:
 #    url: jdbc:mysql://192.168.0.13:3306/?serverTimezone=GMT%2B8




 server:
   port: 8080 #配置端口
   tomcat.uri-encoding: UTF-8
   #配置项目名
   servlet:
     context-path: /HQIndex2
     session:
       timeout: 1800S
 spring:
   datasource:
     druid:
       url: jdbc:mysql://172.16.13.139:3306/fy?useUnicode=true&characterEncoding=utf8&useSSL=false
       username: root
       password: 123456

        #alibaba Druid连接池配置,
       type:  com.alibaba.druid.pool.DruidDataSource
       driver-class-name:  com.mysql.jdbc.Driver
       filters: stat
       maxActive: 20
       initialSize: 1
       maxWait: 60000
       minIdle: 1
       timeBetweenEvictionRunsMillis: 60000
       minEvictableIdleTimeMillis: 300000
       validationQuery: select 'x'
       testWhileIdle: true
       testOnBorrow: false
       testOnReturn: false
       poolPreparedStatements: true
       maxOpenPreparedStatements: 20
   thymeleaf:
       prefix: classpath:/templates/
       check-template-location: true
       suffix: .html
       encoding: UTF-8
       mode: LEGACYHTML5
       cache: false

 mybatis:
   mapper-locations: classpath:mapper/*.xml
   type-aliases-package: com.why.entity

 #pagehelper分页插件
 pagehelper:
   helperDialect: mysql
   reasonable: true
   supportMethodsArguments: true
   params: count=countSql